# server
[[builders]]
key = "uptime_in_seconds"
description = "Number of seconds since Redis server start."
unit = "second"
gauge_type = "u64"

[[builders]]
key = "hz"
description = "The server's current frequency setting."
unit = ""
gauge_type = "u64"

[[builders]]
key = "configured_hz"
description = "The server's configured frequency setting."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lru_clock"
description = "Clock incrementing every minute, for LRU management."
unit = ""
gauge_type = "u64"

[[builders]]
key = "io_threads_active"
description = "Flag indicating if I/O threads are active."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "server_time_usec"
description = "Epoch-based system time with microsecond precision."
unit = "micro seconds"
gauge_type = "u64"

# clients

[[builders]]
key = "connected_clients"
description = "Number of connected clients(excluding connections from replicas)."
unit = ""
gauge_type = "u64"

[[builders]]
key = "cluster_connections"
description = "An approximation of the number of sockets used by the cluster's bus."
unit = ""
gauge_type = "u64"

[[builders]]
key = "maxclients"
description = "The value of the maxclients configuration directive."
unit = ""
gauge_type = "u64"

[[builders]]
key = "client_recent_max_input_buffer"
description = "Biggest input buffer among current client connections."
unit = ""
gauge_type = "u64"

[[builders]]
key = "client_recent_max_output_buffer"
description = "Biggest output buffer among current client connections."
unit = ""
gauge_type = "u64"

[[builders]]
key = "blocked_clients"
description = "Number of clients pending on a blocking call."
unit = ""
gauge_type = "u64"

[[builders]]
key = "tracking_clients"
description = "Number of clients begin tracked."
unit = ""
gauge_type = "u64"

[[builders]]
key = "clients_in_timeout_table"
description = "Number of clients in the clients timeout table."
unit = ""
gauge_type = "u64"

# memory

[[builders]]
key = "used_memory"
description = "Total number of bytes allocated by Redis."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_rss"
description = "Number of bytes that Redis allocated as seen by the OS."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_peak"
description = "Peak memory consumed by Redis."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_overhead"
description = "The sum in bytes of all overheads that the server allocated for managing its internal data structures."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_startup"
description = "Initial amount of memory consumed by Redis at startup."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "total_system_memory"
description = "The total amount of memory that the Redis host has."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_lua"
description = "Number of bytes used by the Lua engine."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_scripts"
description = "Number of bytes used by cached Lua scripts."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "maxmemory"
description = "The value of the maxmemory configuration directive."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_allocated"
description = "Total bytes allocated from the allocator."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_active"
description = "Total bytes in the allocator active pages."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_resident"
description = "Total bytes in resident in the allocator."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_not_counted_for_evict"
description = "Used memory that's not counted for key eviction."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_clients_slaves"
description = "Memory used by replica clients."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_clients_normal"
description = "Memory used by normal clients."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_cluster_links"
description = "Memory used by links to peers on the cluster bus."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_aof_buffer"
description = "Transient memory used for AOF and AOF rewrite buffers."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_replication_backlog"
description = "Memory used by replication backlog."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_total_replication_buffers"
description = "Total memory consumed for replication buffers."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "active_defrag_running"
description = "This indicates whether defragmentation is currently active."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lazyfree_pending_objects"
description = "The number of objects waiting to be freed."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lazyfreed_objects"
description = "The number of objects that has been lazy freed."
unit = ""
gauge_type = "u64"

# persistence

[[builders]]
key = "loading"
description = "Flag indicating if the load of a dump file is on-going."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "async_loading"
description = "Currently loading replication data-set asynchronously while serving old data."
unit = ""
gauge_type = "u64"

[[builders]]
key = "current_cow_peak"
description = "The peak size in bytes of copy-on-write memory while a child fork is running."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "current_cow_size"
description = "The size in bytes of copy-on-write memory while a child fork is running."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "current_cow_size_age"
description = "The age, in seconds, of the current_cow_size value."
unit = "seconds"
gauge_type = "u64"

[[builders]]
key = "current_save_keys_processed"
description = "Number of keys processed by the current save operation."
unit = ""
gauge_type = "u64"

[[builders]]
key = "current_save_keys_total"
description = "Number of keys at the beginning of the current save operation."
unit = ""
gauge_type = "u64"

[[builders]]
key = "rdb_changes_since_last_save"
description = "Number of changes since the last dump."
unit = ""
gauge_type = "u64"

[[builders]]
key = "rdb_bgsave_in_progress"
description = "Flag indicating a RDB save is on-going."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "rdb_last_save_time"
description = "Epoch-based timestamp of last successful RDB save."
unit = "seconds"
gauge_type = "u64"

[[builders]]
key = "rdb_last_bgsave_time_sec"
description = "Duration of the last RDB save operation in seconds."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "rdb_current_bgsave_time_sec"
description = "Duration of the on-going RDB save operation if any."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "rdb_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last RDB save operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "rdb_last_load_keys_expired"
description = "Number volatile keys deleted during the last RDB loading."
unit = ""
gauge_type = "i64"

[[builders]]
key = "rdb_last_load_keys_loaded"
description = "Number of keys loaded during the last RDB loading."
unit = ""
gauge_type = "i64"

[[builders]]
key = "aof_enabled"
description = "Flag indicating AOF logging is activated."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_rewrite_in_progress"
description = "Flag indicating an AOF rewrite operation is on-going."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_rewrite_scheduled"
description = "Flag indicating an AOF rewrite operation will be scheduled once the on-going RDB save is complete."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_last_rewrite_time_sec"
description = "Duration of the last AOF rewrite operation in seconds."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "aof_current_rewrite_time_sec"
description = "Duration of the on-going AOF rewrite operation if any."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "aof_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last AOF rewrite operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "module_fork_in_progress"
description = "Flag indicating a module fork is on-going."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "module_fork_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last module fork operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "aof_rewrites"
description = "Number of AOF rewrites performed since startup."
unit = ""
gauge_type = "i64"

[[builders]]
key = "rdb_saves"
description = "Number of RDB snapshots performed since startup."
unit = ""
gauge_type = "i64"

# cpu

[[builders]]
key = "used_cpu_sys"
description = "Number of system CPU seconds used by the redis server."
unit = ""
gauge_type = "f64"

