# server
[[builders]]
key = "uptime_in_seconds"
description = "Number of seconds since Redis server start."
unit = "second"
gauge_type = "u64"

[[builders]]
key = "hz"
description = "The server's current frequency setting."
unit = ""
gauge_type = "u64"

[[builders]]
key = "configured_hz"
description = "The server's configured frequency setting."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lru_clock"
description = "Clock incrementing every minute, for LRU management."
unit = ""
gauge_type = "u64"

[[builders]]
key = "io_threads_active"
description = "Flag indicating if I/O threads are active."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "server_time_usec"
description = "Epoch-based system time with microsecond precision."
unit = "micro seconds"
gauge_type = "u64"

# clients

[[builders]]
key = "connected_clients"
description = "Number of connected clients(excluding connections from replicas)."
unit = ""
gauge_type = "u64"

[[builders]]
key = "cluster_connections"
description = "An approximation of the number of sockets used by the cluster's bus."
unit = ""
gauge_type = "u64"

[[builders]]
key = "maxclients"
description = "The value of the maxclients configuration directive."
unit = ""
gauge_type = "u64"

[[builders]]
key = "client_recent_max_input_buffer"
description = "Biggest input buffer among current client connections."
unit = ""
gauge_type = "u64"

[[builders]]
key = "client_recent_max_output_buffer"
description = "Biggest output buffer among current client connections."
unit = ""
gauge_type = "u64"

[[builders]]
key = "blocked_clients"
description = "Number of clients pending on a blocking call."
unit = ""
gauge_type = "u64"

[[builders]]
key = "tracking_clients"
description = "Number of clients begin tracked."
unit = ""
gauge_type = "u64"

[[builders]]
key = "clients_in_timeout_table"
description = "Number of clients in the clients timeout table."
unit = ""
gauge_type = "u64"

# memory

[[builders]]
key = "used_memory"
description = "Total number of bytes allocated by Redis."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_rss"
description = "Number of bytes that Redis allocated as seen by the OS."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_peak"
description = "Peak memory consumed by Redis."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_overhead"
description = "The sum in bytes of all overheads that the server allocated for managing its internal data structures."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_startup"
description = "Initial amount of memory consumed by Redis at startup."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "total_system_memory"
description = "The total amount of memory that the Redis host has."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_lua"
description = "Number of bytes used by the Lua engine."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "used_memory_scripts"
description = "Number of bytes used by cached Lua scripts."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "maxmemory"
description = "The value of the maxmemory configuration directive."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_allocated"
description = "Total bytes allocated from the allocator."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_active"
description = "Total bytes in the allocator active pages."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "allocator_resident"
description = "Total bytes in resident in the allocator."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_not_counted_for_evict"
description = "Used memory that's not counted for key eviction."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_clients_slaves"
description = "Memory used by replica clients."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_clients_normal"
description = "Memory used by normal clients."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_cluster_links"
description = "Memory used by links to peers on the cluster bus."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_aof_buffer"
description = "Transient memory used for AOF and AOF rewrite buffers."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_replication_backlog"
description = "Memory used by replication backlog."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "mem_total_replication_buffers"
description = "Total memory consumed for replication buffers."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "active_defrag_running"
description = "This indicates whether defragmentation is currently active."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lazyfree_pending_objects"
description = "The number of objects waiting to be freed."
unit = ""
gauge_type = "u64"

[[builders]]
key = "lazyfreed_objects"
description = "The number of objects that has been lazy freed."
unit = ""
gauge_type = "u64"

# persistence

[[builders]]
key = "loading"
description = "Flag indicating if the load of a dump file is on-going."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "async_loading"
description = "Currently loading replication data-set asynchronously while serving old data."
unit = ""
gauge_type = "u64"

[[builders]]
key = "current_cow_peak"
description = "The peak size in bytes of copy-on-write memory while a child fork is running."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "current_cow_size"
description = "The size in bytes of copy-on-write memory while a child fork is running."
unit = "bytes"
gauge_type = "u64"

[[builders]]
key = "current_cow_size_age"
description = "The age, in seconds, of the current_cow_size value."
unit = "seconds"
gauge_type = "u64"

[[builders]]
key = "current_save_keys_processed"
description = "Number of keys processed by the current save operation."
unit = ""
gauge_type = "u64"

[[builders]]
key = "current_save_keys_total"
description = "Number of keys at the beginning of the current save operation."
unit = ""
gauge_type = "u64"

[[builders]]
key = "rdb_changes_since_last_save"
description = "Number of changes since the last dump."
unit = ""
gauge_type = "u64"

[[builders]]
key = "rdb_bgsave_in_progress"
description = "Flag indicating a RDB save is on-going."
unit = "flag"
gauge_type = "u64"

[[builders]]
key = "rdb_last_save_time"
description = "Epoch-based timestamp of last successful RDB save."
unit = "seconds"
gauge_type = "u64"

[[builders]]
key = "rdb_last_bgsave_time_sec"
description = "Duration of the last RDB save operation in seconds."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "rdb_current_bgsave_time_sec"
description = "Duration of the on-going RDB save operation if any."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "rdb_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last RDB save operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "rdb_last_load_keys_expired"
description = "Number volatile keys deleted during the last RDB loading."
unit = ""
gauge_type = "i64"

[[builders]]
key = "rdb_last_load_keys_loaded"
description = "Number of keys loaded during the last RDB loading."
unit = ""
gauge_type = "i64"

[[builders]]
key = "aof_enabled"
description = "Flag indicating AOF logging is activated."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_rewrite_in_progress"
description = "Flag indicating an AOF rewrite operation is on-going."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_rewrite_scheduled"
description = "Flag indicating an AOF rewrite operation will be scheduled once the on-going RDB save is complete."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "aof_last_rewrite_time_sec"
description = "Duration of the last AOF rewrite operation in seconds."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "aof_current_rewrite_time_sec"
description = "Duration of the on-going AOF rewrite operation if any."
unit = "seconds"
gauge_type = "i64"

[[builders]]
key = "aof_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last AOF rewrite operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "module_fork_in_progress"
description = "Flag indicating a module fork is on-going."
unit = "flag"
gauge_type = "i64"

[[builders]]
key = "module_fork_last_cow_size"
description = "The size in bytes of copy-on-write memory during the last module fork operation."
unit = "bytes"
gauge_type = "i64"

[[builders]]
key = "aof_rewrites"
description = "Number of AOF rewrites performed since startup."
unit = ""
gauge_type = "i64"

[[builders]]
key = "rdb_saves"
description = "Number of RDB snapshots performed since startup."
unit = ""
gauge_type = "i64"

# stats

[[builders]]
key = "total_connections_received"
description = "Total number of connections accepted by the server."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_commands_processed"
description = "Total number of commands processed by the server."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_net_input_bytes"
description = "The total number of bytes read from the network."
unit = "byte"
gauge_type = "i64"

[[builders]]
key = "total_net_output_bytes"
description = "The total number of bytes written to the network."
unit = "byte"
gauge_type = "i64"

[[builders]]
key = "total_net_repl_input_bytes"
description = "The total number of bytes read from the network for replication purposes."
unit = "byte"
gauge_type = "i64"

[[builders]]
key = "total_net_repl_output_bytes"
description = "The total number of bytes written to the network for replication purposes."
unit = "byte"
gauge_type = "i64"

[[builders]]
key = "instantaneous_input_kbps"
description = "The network's read rate per second in KB/sec."
unit = "KB/sec"
gauge_type = "f64"

[[builders]]
key = "instantaneous_output_kbps"
description = "The network's write rate per second in KB/sec."
unit = "KB/sec"
gauge_type = "f64"

[[builders]]
key = "instantaneous_input_repl_kbps"
description = "The network's read rate per second in KB/sec for replication purposes."
unit = "KB/sec"
gauge_type = "f64"

[[builders]]
key = "instantaneous_output_repl_kbps"
description = "The network's write rate per second in KB/sec for replication purposes."
unit = "KB/sec"
gauge_type = "f64"

[[builders]]
key = "rejected_connections"
description = "Number of connections rejected because of maxclients limit."
unit = ""
gauge_type = "i64"

[[builders]]
key = "sync_full"
description = "The number of full resyncs with replicas."
unit = ""
gauge_type = "i64"

[[builders]]
key = "sync_partial_ok"
description = "The number of accepted partial resync requests."
unit = ""
gauge_type = "i64"

[[builders]]
key = "sync_partial_err"
description = "The number of denied partial resync requests."
unit = ""
gauge_type = "i64"

[[builders]]
key = "expired_keys"
description = "Total number of key expiration events."
unit = ""
gauge_type = "i64"

[[builders]]
key = "expired_stale_perc"
description = "The percentage of keys probably expired."
unit = ""
gauge_type = "f64"

[[builders]]
key = "expired_time_cap_reached_count"
description = "The count of times that active expiry cycles have stopped early."
unit = ""
gauge_type = "i64"

[[builders]]
key = "expire_cycle_cpu_milliseconds"
description = "The cumulative amount of time spend on active expiry cycles."
unit = "ms"
gauge_type = "i64"

[[builders]]
key = "evicted_keys"
description = "Number of evicted keys due to maxmemory limit."
unit = ""
gauge_type = "i64"

[[builders]]
key = "evicted_clients"
description = "Number of evicted clients due to maxmemory-clients limit."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_eviction_exceeded_time"
description = "Total time used_memory was greater than maxmemory since server startup, in milliseconds."
unit = "ms"
gauge_type = "i64"

[[builders]]
key = "current_eviction_exceeded_time"
description = "The time passed since used_memory last rose above maxmemory, in milliseconds."
unit = "ms"
gauge_type = "i64"

[[builders]]
key = "keyspace_hits"
description = "Number of successful lookup of keys in the main dictionary."
unit = ""
gauge_type = "i64"

[[builders]]
key = "keyspace_misses"
description = "Number of failed lookup of keys in the main dictionary."
unit = ""
gauge_type = "i64"

[[builders]]
key = "pubsub_channels"
description = "Global number of pub/sub channels with client subscriptions."
unit = ""
gauge_type = "i64"

[[builders]]
key = "pubsub_patterns"
description = "Global number of pub/sub pattern with client subscriptions."
unit = ""
gauge_type = "i64"

[[builders]]
key = "pubsubshard_channels"
description = "Global number of pub/sub shard channels with client subscriptions."
unit = ""
gauge_type = "i64"

[[builders]]
key = "latest_fork_usec"
description = "Duration of the latest fork operation in microseconds."
unit = "us"
gauge_type = "i64"

[[builders]]
key = "total_forks"
description = "Total number of fork operations since the server start."
unit = ""
gauge_type = "i64"

[[builders]]
key = "migrate_cached_sockets"
description = "The number of sockets open for MIGRATE purposes."
unit = ""
gauge_type = "i64"

[[builders]]
key = "slave_expires_tracked_keys"
description = "The number of keys tracked for expiry purposes."
unit = ""
gauge_type = "i64"

[[builders]]
key = "active_defrag_hits"
description = "Number of value reallocations performed by the active defragmentation process."
unit = ""
gauge_type = "i64"

[[builders]]
key = "active_defrag_misses"
description = "Number of aborted value reallocations started by the active defragmentation process."
unit = ""
gauge_type = "i64"

[[builders]]
key = "active_defrag_key_hits"
description = "Number of keys that were actively defragmented."
unit = ""
gauge_type = "i64"

[[builders]]
key = "active_defrag_key_misses"
description = "Number of keys that were skipped by the active defragmentation process."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_active_defrag_time"
description = "Total time memory fragmentation was over the limit, in milliseconds."
unit = "ms"
gauge_type = "i64"

[[builders]]
key = "current_active_defrag_time"
description = "The time passed since memory fragmentation last was over the limit, in milliseconds."
unit = "ms"
gauge_type = "i64"

[[builders]]
key = "tracking_total_keys"
description = "Number of keys being tracked by the server."
unit = ""
gauge_type = "i64"

[[builders]]
key = "tracking_total_items"
description = "Number of items, that is the sum of clients number for each key, that are being tracked."
unit = ""
gauge_type = "i64"

[[builders]]
key = "tracking_total_prefixes"
description = "Number of tracked prefixes in server's prefix table."
unit = ""
gauge_type = "i64"

[[builders]]
key = "unexpected_error_replies"
description = "Number of unexpected error replicas, that are types of errors from an AOF load or replication."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_error_replies"
description = "Total number of issued error replicas, that is the sum of rejected commands and failed commands."
unit = ""
gauge_type = "i64"

[[builders]]
key = "dump_payload_sanitizations"
description = "Total number of dump payload deep integrity validations."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_reads_processed"
description = "Total number of read events processed."
unit = ""
gauge_type = "i64"

[[builders]]
key = "total_writes_processed"
description = "Total number of write events processed."
unit = ""
gauge_type = "i64"

[[builders]]
key = "io_threaded_reads_processed"
description = "Number of read events processed by the main and I/O threads."
unit = ""
gauge_type = "i64"

[[builders]]
key = "io_threaded_writes_processed"
description = "Number of write events processed by the main and I/O threads."
unit = ""
gauge_type = "i64"

# cpu

[[builders]]
key = "used_cpu_sys"
description = "System CPU consumed by the Redis server."
unit = ""
gauge_type = "f64"

[[builders]]
key = "used_cpu_user"
description = "User CPU consumed by the Redis server."
unit = ""
gauge_type = "f64"

[[builders]]
key = "used_cpu_sys_children"
description = "System CPU consumed by the background processes."
unit = ""
gauge_type = "f64"

[[builders]]
key = "used_cpu_user_children"
description = "User CPU consumed by the background processes."
unit = ""
gauge_type = "f64"

[[builders]]
key = "used_cpu_sys_main_thread"
description = "System CPU consumed by the Redis server main thread."
unit = ""
gauge_type = "f64"

[[builders]]
key = "used_cpu_user_main_thread"
description = "User CPU consumed by the Redis server main thread."
unit = ""
gauge_type = "f64"

